"""Baseline schema - reconciles existing models to today's actual schema

This is a hand-authored baseline, not an autogenerated diff (there was no
database reachable to diff against, and no prior migration history existed).
It captures every table currently declared by the ORM models in
backend/models/database.py as of the date below, so that this revision
becomes the reconciliation point going forward: existing databases should be
stamped at this revision (`alembic stamp 0001`) rather than have it run
against them, and only brand-new databases should actually `alembic upgrade`
through it.

Column nullability mirrors each model's `Mapped[...]` annotation (Optional
=> nullable). `server_default` is only set where the model itself declares
`server_default=` (the `created_at`/`updated_at` "now()" columns); columns
that only declare a Python-side `default=` (e.g. `default="USD"`,
`default=list`, `default=False`, uuid.uuid4 id defaults, etc.) are left
without a DB-level DEFAULT, because that is exactly what the ORM currently
does - SQLAlchemy's `default=` is applied by the ORM before INSERT, it does
not emit a DDL `DEFAULT` clause. If you want these enforced at the database
level too (e.g. for safety against raw SQL inserts), that's a deliberate
follow-up change, not something this baseline should silently invent.

Revision ID: 0001
Revises:
Create Date: 2026-08-14

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ── Core recruiting flow ────────────────────────────────────────────
    op.create_table(
        "verified_jobs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("organization", sa.String(255), nullable=False),
        sa.Column("location", sa.String(255), nullable=True),
        sa.Column("work_mode", sa.String(50), nullable=True),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(10), nullable=True),
        sa.Column("experience_required", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("requirements", postgresql.JSONB(), nullable=True),
        sa.Column("technologies", postgresql.JSONB(), nullable=True),
        sa.Column("application_link", sa.Text(), nullable=True),
        sa.Column("career_page_link", sa.Text(), nullable=True),
        sa.Column("recruiter_name", sa.String(255), nullable=True),
        sa.Column("recruiter_linkedin", sa.Text(), nullable=True),
        sa.Column("verification_status", sa.String(50), nullable=False),
        sa.Column("level_up", sa.Boolean(), nullable=False),
        sa.Column("match_score", sa.Integer(), nullable=True),
        sa.Column("posted_date", sa.String(30), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "candidate_profiles",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("current_role", sa.String(255), nullable=True),
        sa.Column("current_salary", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(10), nullable=True),
        sa.Column("experience_years", sa.Integer(), nullable=True),
        sa.Column("current_location", sa.String(255), nullable=True),
        sa.Column("preferred_locations", postgresql.JSONB(), nullable=True),
        sa.Column("skills", postgresql.JSONB(), nullable=True),
        sa.Column("frameworks", postgresql.JSONB(), nullable=True),
        sa.Column("languages", postgresql.JSONB(), nullable=True),
        sa.Column("cicd_tools", postgresql.JSONB(), nullable=True),
        sa.Column("ai_tools", postgresql.JSONB(), nullable=True),
        sa.Column("certifications", postgresql.JSONB(), nullable=True),
        sa.Column("work_mode", sa.String(50), nullable=True),
        sa.Column("base_resume_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    # ── Career graph (Phase 1) - parents before children ────────────────
    op.create_table(
        "career_graphs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("health_score", sa.Integer(), nullable=False),
        sa.Column("health_breakdown", postgresql.JSONB(), nullable=True),
        sa.Column("market_position_score", sa.Integer(), nullable=False),
        sa.Column("demand_score", sa.Integer(), nullable=False),
        sa.Column("rarity_score", sa.Integer(), nullable=False),
        sa.Column("percentile_rank", sa.Integer(), nullable=False),
        sa.Column("onboarding_complete", sa.Boolean(), nullable=False),
        sa.Column("last_computed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index(
        "ix_career_graphs_user_id", "career_graphs", ["user_id"], unique=True
    )

    # ── Company intelligence (Phase 2) ──────────────────────────────────
    op.create_table(
        "companies",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("domain", sa.String(255), nullable=True, unique=True),
        sa.Column("industry", sa.String(100), nullable=True),
        sa.Column("size_range", sa.String(50), nullable=True),
        sa.Column("founded_year", sa.Integer(), nullable=True),
        sa.Column("hq_location", sa.String(255), nullable=True),
        sa.Column("remote_policy", sa.String(50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("linkedin_url", sa.Text(), nullable=True),
        sa.Column("funding_stage", sa.String(50), nullable=True),
        sa.Column("last_funding_amount", sa.Integer(), nullable=True),
        sa.Column("last_funding_date", sa.String(20), nullable=True),
        sa.Column("glassdoor_rating", sa.Float(), nullable=True),
        sa.Column("glassdoor_review_count", sa.Integer(), nullable=True),
        sa.Column("culture_score", sa.Integer(), nullable=True),
        sa.Column("growth_score", sa.Integer(), nullable=True),
        sa.Column("layoff_risk_score", sa.Integer(), nullable=True),
        sa.Column("interview_difficulty_avg", sa.Float(), nullable=True),
        sa.Column("tech_stack", postgresql.JSONB(), nullable=True),
        sa.Column("salary_ranges", postgresql.JSONB(), nullable=True),
        sa.Column("interview_process", postgresql.JSONB(), nullable=True),
        sa.Column("insider_report", sa.Text(), nullable=True),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_companies_name", "companies", ["name"], unique=False)

    # ── Learning engine (Phase 3) ───────────────────────────────────────
    op.create_table(
        "learning_paths",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("skill_name", sa.String(255), nullable=False),
        sa.Column("target_level", sa.Integer(), nullable=False),
        sa.Column("current_level", sa.Integer(), nullable=False),
        sa.Column("estimated_hours", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(50), nullable=False),
        sa.Column("progress_pct", sa.Integer(), nullable=False),
        sa.Column("resources", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_learning_paths_user_id", "learning_paths", ["user_id"], unique=False)

    op.create_table(
        "learning_resources",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("skill_name", sa.String(255), nullable=False),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("provider", sa.String(100), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("type", sa.String(50), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("difficulty", sa.String(50), nullable=True),
        sa.Column("is_free", sa.Boolean(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("tags", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_learning_resources_skill_name", "learning_resources", ["skill_name"], unique=False)

    # ── Portfolio (Phase 6) ─────────────────────────────────────────────
    op.create_table(
        "portfolios",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("slug", sa.String(100), nullable=False, unique=True),
        sa.Column("headline", sa.String(255), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("ai_bio", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("linkedin_url", sa.Text(), nullable=True),
        sa.Column("github_url", sa.Text(), nullable=True),
        sa.Column("website_url", sa.Text(), nullable=True),
        sa.Column("theme", sa.String(50), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("skills", postgresql.JSONB(), nullable=True),
        sa.Column("certifications", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_portfolios_user_id", "portfolios", ["user_id"], unique=True)

    # ── Notifications (Phase 7) ─────────────────────────────────────────
    op.create_table(
        "notifications",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("type", sa.String(50), nullable=False),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("action_url", sa.Text(), nullable=True),
        sa.Column("extra_data", postgresql.JSONB(), nullable=True),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"], unique=False)

    # ── Interview story bank ────────────────────────────────────────────
    op.create_table(
        "master_stories",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("requirement", sa.String(500), nullable=False),
        sa.Column("story_theme", sa.Text(), nullable=False),
        sa.Column("situation", sa.Text(), nullable=True),
        sa.Column("task", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("reflection", sa.Text(), nullable=True),
        sa.Column("archetype_tags", postgresql.JSONB(), nullable=True),
        sa.Column("source_job", sa.String(255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_master_stories_user_id", "master_stories", ["user_id"], unique=False)

    # ── Autopilot (Phase 5) ─────────────────────────────────────────────
    op.create_table(
        "autopilot_settings",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("min_fit_score", sa.Integer(), nullable=False),
        sa.Column("max_per_day", sa.Integer(), nullable=False),
        sa.Column("exclude_companies", postgresql.JSONB(), nullable=True),
        sa.Column("require_approval", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_autopilot_settings_user_id", "autopilot_settings", ["user_id"], unique=True)

    op.create_table(
        "autopilot_queue",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("job_title", sa.String(255), nullable=False),
        sa.Column("job_org", sa.String(255), nullable=True),
        sa.Column("job_location", sa.String(255), nullable=True),
        sa.Column("fit_score", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(50), nullable=False),
        sa.Column("generated_resume", sa.Text(), nullable=True),
        sa.Column("generated_cover_letter", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("actioned_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_autopilot_queue_user_id", "autopilot_queue", ["user_id"], unique=False)

    # ── Tables that reference the ones created above ────────────────────
    op.create_table(
        "resume_history",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("verified_jobs.id"), nullable=True),
        sa.Column("job_title", sa.String(255), nullable=True),
        sa.Column("organization", sa.String(255), nullable=True),
        sa.Column("ats_score", sa.Integer(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("bullets", postgresql.JSONB(), nullable=True),
        sa.Column("skills_grouped", postgresql.JSONB(), nullable=True),
        sa.Column("pdf_base64", sa.Text(), nullable=True),
        sa.Column("docx_base64", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_resume_history_user_id", "resume_history", ["user_id"], unique=False)

    op.create_table(
        "applications",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("verified_jobs.id"), nullable=True),
        sa.Column("profile_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("candidate_profiles.id"), nullable=True),
        sa.Column("status", sa.String(50), nullable=False),
        sa.Column("date_applied", sa.DateTime(timezone=True), nullable=True),
        sa.Column("follow_up_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("evaluation_score", sa.Float(), nullable=True),
        sa.Column("archetype", sa.String(100), nullable=True),
        sa.Column("evaluation_report", postgresql.JSONB(), nullable=True),
        sa.Column("generated_resume_url", sa.Text(), nullable=True),
        sa.Column("generated_cover_letter_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "career_skills",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("graph_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("career_graphs.id"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("skill_name", sa.String(255), nullable=False),
        sa.Column("category", sa.String(100), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("last_used_year", sa.Integer(), nullable=True),
        sa.Column("trending_score", sa.Float(), nullable=False),
        sa.Column("years_experience", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_career_skills_user_id", "career_skills", ["user_id"], unique=False)
    op.create_index("ix_career_skills_user_skill", "career_skills", ["user_id", "skill_name"], unique=False)

    op.create_table(
        "career_goals",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("graph_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("career_graphs.id"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("target_role", sa.String(255), nullable=True),
        sa.Column("target_company", sa.String(255), nullable=True),
        sa.Column("target_salary_min", sa.Integer(), nullable=True),
        sa.Column("target_salary_max", sa.Integer(), nullable=True),
        sa.Column("target_location", sa.String(255), nullable=True),
        sa.Column("timeline_months", sa.Integer(), nullable=True),
        sa.Column("work_mode", sa.String(50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_career_goals_user_id", "career_goals", ["user_id"], unique=False)

    op.create_table(
        "career_milestones",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("graph_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("career_graphs.id"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("type", sa.String(50), nullable=False),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("company", sa.String(255), nullable=True),
        sa.Column("milestone_date", sa.String(20), nullable=True),
        sa.Column("impact_statement", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_career_milestones_user_id", "career_milestones", ["user_id"], unique=False)

    op.create_table(
        "company_interview_reports",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("submitted_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("role", sa.String(255), nullable=False),
        sa.Column("interview_rounds", sa.Integer(), nullable=True),
        sa.Column("difficulty", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(50), nullable=True),
        sa.Column("questions", postgresql.JSONB(), nullable=True),
        sa.Column("process_description", sa.Text(), nullable=True),
        sa.Column("tips", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "learning_completions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("path_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("learning_paths.id"), nullable=True),
        sa.Column("resource_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("learning_resources.id"), nullable=True),
        sa.Column("resource_url", sa.Text(), nullable=True),
        sa.Column("skill_name", sa.String(255), nullable=False),
        sa.Column("rating_given", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_learning_completions_user_id", "learning_completions", ["user_id"], unique=False)

    op.create_table(
        "portfolio_projects",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("portfolio_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("portfolios.id"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ai_impact", sa.Text(), nullable=True),
        sa.Column("tech_stack", postgresql.JSONB(), nullable=True),
        sa.Column("demo_url", sa.Text(), nullable=True),
        sa.Column("github_url", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("featured", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_portfolio_projects_user_id", "portfolio_projects", ["user_id"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # Reverse creation order so FK-referencing tables drop before the
    # tables they reference.
    op.drop_table("portfolio_projects")
    op.drop_table("learning_completions")
    op.drop_table("company_interview_reports")
    op.drop_table("career_milestones")
    op.drop_table("career_goals")
    op.drop_table("career_skills")
    op.drop_table("applications")
    op.drop_table("resume_history")

    op.drop_table("autopilot_queue")
    op.drop_table("autopilot_settings")
    op.drop_table("master_stories")
    op.drop_table("notifications")
    op.drop_table("portfolios")
    op.drop_table("learning_resources")
    op.drop_table("learning_paths")
    op.drop_table("companies")
    op.drop_table("career_graphs")
    op.drop_table("candidate_profiles")
    op.drop_table("verified_jobs")
