import {
  Job,
  Application,
  SkillGapItem,
  RoadmapPhase,
  CandidateProfile,
} from "./types";

// ─── Demo Candidate Profile ────────────────────────────────────────────────────
export const demoProfile: CandidateProfile = {
  name: "",
  currentRole: "",
  currentSalary: 0,
  currency: "USD",
  experienceYears: 0,
  workMode: "Any",
  currentLocation: "",
  preferredLocations: [],
  skills: [],
  frameworks: [],
  languages: [],
  cicdTools: [],
  certifications: [],
};

// ─── Mock Jobs ─────────────────────────────────────────────────────────────────
export const mockJobs: Job[] = [
  {
    id: "j001",
    title: "Lead QA Automation Engineer",
    organization: "Stripe",
    location: "Remote",
    workMode: "Remote",
    salaryMin: 130000,
    salaryMax: 160000,
    currency: "USD",
    experienceRequired: 7,
    technologies: ["Playwright", "TypeScript", "GitHub Actions", "K6", "Docker"],
    description:
      "Lead the QA automation strategy for Stripe's payment infrastructure. You will design test frameworks, mentor engineers, and own quality across multiple product teams. Seek a candidate with strong experience in Playwright, API automation, and CI/CD pipelines.",
    careerPageLink: "https://stripe.com/jobs",
    applicationLink: "https://stripe.com/jobs/listing/lead-qa",
    verificationStatus: "VERIFIED",
    postedDate: "2026-03-14",
    matchScore: 88,
    levelUp: true,
    source: "LinkedIn",
    recruiterName: "Sarah Mitchell",
    recruiterLinkedIn: "https://linkedin.com/in/sarahmitchell",
  },
  {
    id: "j002",
    title: "Principal SDET",
    organization: "Atlassian",
    location: "Sydney, Australia (Remote OK)",
    workMode: "Remote",
    salaryMin: 140000,
    salaryMax: 175000,
    currency: "USD",
    experienceRequired: 8,
    technologies: ["Selenium", "Pytest", "AWS", "Jenkins", "REST Assured"],
    description:
      "Drive quality engineering initiatives across Atlassian's cloud platform. Design scalable automation frameworks, define quality benchmarks, and collaborate with engineering leadership. Strong background in both UI and API automation required.",
    careerPageLink: "https://www.atlassian.com/company/careers",
    applicationLink: "https://www.atlassian.com/careers",
    verificationStatus: "VERIFIED",
    postedDate: "2026-03-15",
    matchScore: 85,
    levelUp: true,
    source: "Indeed",
    recruiterName: "James Park",
    recruiterLinkedIn: "https://linkedin.com/in/jamespark",
  },
  {
    id: "j003",
    title: "QA Lead – Automation",
    organization: "ThoughtWorks",
    location: "Bangalore, India",
    workMode: "Hybrid",
    salaryMin: 2500000,
    salaryMax: 3500000,
    currency: "INR",
    experienceRequired: 6,
    technologies: ["Playwright", "Cypress", "Java", "REST API", "CI/CD"],
    description:
      "Lead automation quality practices for enterprise clients. Define testing strategies, coach teams on BDD and automated testing, manage release quality gates. Excellent client-facing communication required.",
    careerPageLink: "https://www.thoughtworks.com/careers",
    applicationLink: "https://www.thoughtworks.com/careers",
    verificationStatus: "VERIFIED",
    postedDate: "2026-03-13",
    matchScore: 91,
    levelUp: true,
    source: "Naukri",
    recruiterName: "Priya Sharma",
    recruiterLinkedIn: "https://linkedin.com/in/priyasharma",
  },
  {
    id: "j004",
    title: "Senior QA Automation Engineer",
    organization: "Flipkart",
    location: "Bangalore, India",
    workMode: "Hybrid",
    salaryMin: 1800000,
    salaryMax: 2800000,
    currency: "INR",
    experienceRequired: 6,
    technologies: ["Selenium", "TestNG", "Java", "Appium", "Jenkins"],
    description:
      "Join Flipkart's quality engineering team to automate e-commerce platform testing at scale. Build reliable test frameworks for mobile and web, integrate with CI/CD pipelines, and deliver high-quality releases.",
    careerPageLink: "https://www.flipkart.com/careers",
    applicationLink: "https://www.flipkart.com/careers",
    verificationStatus: "VERIFIED",
    postedDate: "2026-03-12",
    matchScore: 84,
    levelUp: false,
    source: "Naukri",
    recruiterName: "Rohan Mehta",
    recruiterLinkedIn: "https://linkedin.com/in/rohanmehta",
  },
  {
    id: "j005",
    title: "QA Engineering Manager",
    organization: "Razorpay",
    location: "Bangalore, India",
    workMode: "Hybrid",
    salaryMin: 3500000,
    salaryMax: 5000000,
    currency: "INR",
    experienceRequired: 9,
    technologies: ["Selenium", "Playwright", "Python", "AWS", "Kubernetes"],
    description:
      "Lead a team of 8 QA engineers across Razorpay's payment gateway products. Define quality KPIs, manage roadmaps, partner with product and engineering, and drive automation coverage to 80%+.",
    careerPageLink: "https://razorpay.com/jobs",
    applicationLink: "https://razorpay.com/jobs",
    verificationStatus: "VERIFIED",
    postedDate: "2026-03-11",
    matchScore: 72,
    levelUp: true,
    source: "Glassdoor",
    recruiterName: "Ananya Krishnan",
    recruiterLinkedIn: "https://linkedin.com/in/ananyakrishnan",
  },
  {
    id: "j006",
    title: "Automation Test Lead",
    organization: "EPAM Systems",
    location: "Remote (UK/EU)",
    workMode: "Remote",
    salaryMin: 65000,
    salaryMax: 85000,
    currency: "GBP",
    experienceRequired: 7,
    technologies: ["Playwright", "TypeScript", "Azure DevOps", "Robot Framework"],
    description:
      "Lead Test Automation practice for financial services clients. Architect frameworks, conduct code reviews, and own test strategy for multi-team agile projects.",
    careerPageLink: "https://www.epam.com/careers",
    applicationLink: "https://jobs.epam.com",
    verificationStatus: "VERIFIED",
    postedDate: "2026-03-10",
    matchScore: 80,
    levelUp: true,
    source: "LinkedIn",
    recruiterName: "Dan Cooper",
    recruiterLinkedIn: "https://linkedin.com/in/dancooper",
  },
  {
    id: "j007",
    title: "Senior QA Engineer – API & Performance",
    organization: "Zoho Corporation",
    location: "Chennai, India",
    workMode: "On-site",
    salaryMin: 1500000,
    salaryMax: 2200000,
    currency: "INR",
    experienceRequired: 5,
    technologies: ["REST Assured", "JMeter", "Postman", "Java", "Jenkins"],
    description:
      "We are looking for a Senior QA Engineer specializing in API testing, performance testing, and automation for Zoho's SaaS products used by 80M+ users globally.",
    careerPageLink: "https://careers.zoho.com",
    applicationLink: "https://careers.zoho.com",
    verificationStatus: "VERIFIED",
    postedDate: "2026-03-09",
    matchScore: 78,
    levelUp: false,
    source: "Indeed",
    recruiterName: "Kavitha R",
    recruiterLinkedIn: "https://linkedin.com/in/kavithar",
  },
  {
    id: "j008",
    title: "Director of Quality Engineering",
    organization: "PhonePe",
    location: "Bangalore, India",
    workMode: "Hybrid",
    salaryMin: 6000000,
    salaryMax: 9000000,
    currency: "INR",
    experienceRequired: 12,
    technologies: ["Selenium", "Playwright", "Kotlin", "AWS", "Kubernetes"],
    description:
      "Shape the quality engineering culture at PhonePe. Own testing strategy for 500M+ user platform, build a world-class QA function, and influence product decisions at the executive level.",
    careerPageLink: "https://phonepe.com/en-in/careers.html",
    applicationLink: "https://phonepe.com/en-in/careers.html",
    verificationStatus: "VERIFIED",
    postedDate: "2026-03-08",
    matchScore: 60,
    levelUp: true,
    source: "Glassdoor",
    recruiterName: "Deepak Nair",
    recruiterLinkedIn: "https://linkedin.com/in/deepaknair",
  },
  {
    id: "j009",
    title: "QA Automation Engineer",
    organization: "TechStart Solutions",
    location: "Remote (India/Asia)",
    workMode: "Remote",
    salaryMin: 1200000,
    salaryMax: 1800000,
    currency: "INR",
    experienceRequired: 3,
    technologies: ["Selenium", "Pytest", "Jenkins", "Postman", "Git"],
    description:
      "Growing product startup looking for a QA Automation Engineer to own test quality across our web and mobile platforms. You'll build automation from scratch, integrate with CI/CD, and work directly with developers in a fast-paced agile environment. Ideal for someone who likes full ownership.",
    careerPageLink: "https://techstartsolutions.com/careers",
    applicationLink: "https://techstartsolutions.com/careers",
    verificationStatus: "UNVERIFIED",
    postedDate: "2026-03-16",
    matchScore: 70,
    levelUp: false,
    source: "Remotive",
  },
];

// ─── Mock Applications ─────────────────────────────────────────────────────────
export const mockApplications: Application[] = [
  {
    id: "a001",
    jobId: "j003",
    job: mockJobs[2],
    status: "Interview",
    dateApplied: "2026-03-10",
    followUpDate: "2026-03-18",
    notes: "Technical round scheduled for 18th March at 3PM IST",
  },
  {
    id: "a002",
    jobId: "j001",
    job: mockJobs[0],
    status: "Applied",
    dateApplied: "2026-03-14",
    followUpDate: "2026-03-21",
    notes: "Applied via LinkedIn. Follow up if no response by 21st.",
  },
  {
    id: "a003",
    jobId: "j004",
    job: mockJobs[3],
    status: "Assessment",
    dateApplied: "2026-03-09",
    followUpDate: "2026-03-17",
    notes: "Coding assessment due 17th March",
  },
  {
    id: "a004",
    jobId: "j007",
    job: mockJobs[6],
    status: "Rejected",
    dateApplied: "2026-02-28",
    notes: "Rejected after final round - location constraint",
  },
  {
    id: "a005",
    jobId: "j006",
    job: mockJobs[5],
    status: "Offer",
    dateApplied: "2026-03-01",
    notes: "Offer letter received – deciding by 20th March",
  },
];

// ─── Skill Gaps ────────────────────────────────────────────────────────────────
export const mockSkillGaps: SkillGapItem[] = [
  { skill: "Playwright", category: "UI Automation", demandScore: 94, inProfile: true, priority: "High" },
  { skill: "TypeScript", category: "Language", demandScore: 89, inProfile: false, priority: "High", learningResource: "typescriptlang.org" },
  { skill: "K6 / Gatling", category: "Performance", demandScore: 75, inProfile: false, priority: "High", learningResource: "k6.io/docs" },
  { skill: "Kubernetes", category: "DevOps", demandScore: 82, inProfile: false, priority: "High", learningResource: "kubernetes.io/docs" },
  { skill: "Cypress", category: "UI Automation", demandScore: 78, inProfile: false, priority: "Medium", learningResource: "cypress.io" },
  { skill: "Robot Framework", category: "Automation", demandScore: 65, inProfile: false, priority: "Medium", learningResource: "robotframework.org" },
  { skill: "AWS (Testing in Cloud)", category: "Cloud", demandScore: 88, inProfile: false, priority: "High", learningResource: "aws.amazon.com/training" },
  { skill: "Appium", category: "Mobile Automation", demandScore: 70, inProfile: false, priority: "Medium", learningResource: "appium.io" },
  { skill: "GitHub Actions", category: "CI/CD", demandScore: 85, inProfile: true, priority: "High" },
  { skill: "REST Assured", category: "API Testing", demandScore: 80, inProfile: false, priority: "Medium", learningResource: "rest-assured.io" },
];

// ─── Roadmap ───────────────────────────────────────────────────────────────────
export const mockRoadmap: RoadmapPhase[] = [
  {
    phase: 1,
    title: "Modern Automation Frameworks",
    duration: "4–6 weeks",
    skills: ["Playwright", "TypeScript", "Cypress"],
    resources: ["playwright.dev", "typescriptlang.org", "cypress.io"],
  },
  {
    phase: 2,
    title: "Advanced API & Performance Testing",
    duration: "4–6 weeks",
    skills: ["K6", "REST Assured", "Postman Collections", "Contract Testing"],
    resources: ["k6.io", "rest-assured.io", "pact.io"],
  },
  {
    phase: 3,
    title: "DevOps & Cloud Integration",
    duration: "6–8 weeks",
    skills: ["Kubernetes", "AWS", "Terraform basics", "Monitoring (Grafana)"],
    resources: ["kubernetes.io", "aws.amazon.com/training", "grafana.com"],
  },
];

// ─── Hiring Heatmap Data ───────────────────────────────────────────────────────
export const heatmapData = [
  { city: "Bangalore", lat: 12.97, lng: 77.59, count: 234, country: "IN" },
  { city: "Hyderabad", lat: 17.38, lng: 78.47, count: 187, country: "IN" },
  { city: "Remote (Global)", lat: 20, lng: 0, count: 412, country: "GL" },
  { city: "London", lat: 51.51, lng: -0.13, count: 156, country: "UK" },
  { city: "Sydney", lat: -33.87, lng: 151.21, count: 98, country: "AU" },
  { city: "San Francisco", lat: 37.77, lng: -122.42, count: 89, country: "US" },
  { city: "Chennai", lat: 13.08, lng: 80.27, count: 143, country: "IN" },
  { city: "Pune", lat: 18.52, lng: 73.86, count: 121, country: "IN" },
];
